name: Deploy website

on:
  pull_request:
    branches: main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: Github Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v3
        uses: actions/configure-pages@v3
        uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: nightly
            components: rustfmt, clippy
            override: true
        uses: jetli/trunk-action@v0.4.0
          with:
            version: 'latest'
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcs

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      
      - name: Build
        run: |
          trunk build
  
      - name: Deploy
        id: deployment
        uses: actions/upload-pages-artifact@v1
          with:
            path: './dist'
        uses: actions/deploy-pages@v2